# call from repo root

# FROM nvidia/cuda:10.0-devel AS build
# FROM nvcr.io/nvidia/l4t-pytorch:r32.6.1-pth1.9-py3 AS build
FROM nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.7-py3 AS build

WORKDIR /tmp/build

COPY . kubeshare

# RUN apt update && \
#     apt install -y git && \
#     git clone https://github.com/NTHU-LSALAB/Gemini.git && cd Gemini && \
#     make -C src
# RUN apt update && \
#     apt install -y git && \
#     git clone https://gitee.com/crawler995/Gemini.git && cd Gemini && \
#     make -C src
# COPY Gemini-master ./Gemini
COPY Gemini-v1.0 ./Gemini
RUN cd Gemini && cp src/Makefile-arm64 src/Makefile && make -C src DEBUG=1

FROM python:3.8.1-buster

RUN pip3 install inotify

ENV NVIDIA_VISIBLE_DEVICES      all
ENV NVIDIA_DRIVER_CAPABILITIES  utility

COPY docker/lib/libdl.so.2          /lib
COPY docker/lib/libnvidia-ml.so.1   /lib

COPY --from=build /tmp/build/kubeshare/docker/kubeshare-gemini-scheduler/launcher-multigpus.sh /launcher-multigpus.sh
COPY --from=build /tmp/build/kubeshare/docker/kubeshare-gemini-scheduler/launcher.py /launcher.py
COPY --from=build /tmp/build/Gemini/bin/gem-schd /gem-schd
COPY --from=build /tmp/build/Gemini/bin/gem-pmgr /gem-pmgr

CMD ["/launcher-multigpus.sh", "/kubeshare/scheduler/config", "/kubeshare/scheduler/podmanagerport"]
