# call from repo root

# FROM nvidia/cuda:10.0-devel AS build
# FROM nvcr.io/nvidia/l4t-pytorch:r32.6.1-pth1.9-py3 AS build
FROM nvcr.io/nvidia/l4t-pytorch:r32.5.0-pth1.7-py3 AS build

WORKDIR /tmp/build

# RUN apt update && \
#     apt install -y git && \
#     git clone https://github.com/NTHU-LSALAB/Gemini.git && cd Gemini && \
#     make -C src
# RUN apt update && \
#     apt install -y git && \
#     git clone https://gitee.com/crawler995/Gemini.git && cd Gemini && \
#     make -C src

# COPY Gemini-master ./Gemini
COPY Gemini-v1.0 ./Gemini
RUN cd Gemini && cp src/Makefile-arm64 src/Makefile && make -C src

# FROM busybox:1.31.1-glibc
FROM alpine:3.9

COPY --from=build /tmp/build/Gemini/lib/libgemhook.so.1 /libgemhook.so.1

CMD ["cp", "/libgemhook.so.1", "/kubeshare/library/libgemhook.so.1"]
